version: "3"

volumes:
  screener:

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
      - RABBITMQ_DEFAULT_VHOST=vhost
    ports:
      - "15671:15672"
      - "5672:5672"

  redis:
    image: redis:7.0.12-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6378:6379"

  #  screener:
  #    build: .
  ##    command: python manage.py runserver 0.0.0.0:8000
  #    volumes:
  #      - .:/app
  #    ports:
  #      - 8000:8000
  #    entrypoint: [ "/bin/sh", "-c", "python core/starterfile.py" ]
  #    restart: "always"
